export const zh: ST.SuitContent = {
	refresh: "获取新Torrent",
	torrentListTitle: "Torrent列表",
	appTitle: "用Torrent<br/>共享文件",
	upload: "选择文件",
	noFile: "未选择文件",
	multiFiles: "选择了多个文件",
	uploadSuccessful: "上传成功",
	processing: "处理中",
	uploadFailure: "上传失败",
	shareListTitle: "共享文件",
	downloadListTitle: "下载文件",
	authorLabel: "作者",
	timeLabel: "上传时间",
	languageType: "EN",
	export: "导出",
	import: "导入",
};
export const en: ST.SuitContent = {
	refresh: "Get new",
	torrentListTitle: "Torrent list",
	appTitle: "Share <br/> Torrent",
	upload: "Upload",
	noFile: "Should select files (audio or image)",
	multiFiles: "Multi-files were selected",
	uploadSuccessful: "upload success",
	uploadFailure: "upload fail",
	processing: "processing",
	downloadListTitle: "Download files",
	shareListTitle: "Share files",
	authorLabel: "author",
	timeLabel: "upload time",
	languageType: "中文",
	export: "export",
	import: "import",
};
